# Generated by Django 5.1 on 2024-08-15 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Livre",
            fields=[
                ("id_livre", models.AutoField(primary_key=True, serialize=False)),
                ("titre_livre", models.CharField(max_length=100)),
                ("auteur_livre", models.CharField(max_length=100)),
                ("date_publication_livre", models.DateField()),
                ("etat_livre", models.BooleanField(default=True)),
                ("nombre_exemplaire", models.IntegerField()),
                ("nombre_page", models.IntegerField()),
                (
                    "image_couverture_livre",
                    models.ImageField(blank=True, null=True, upload_to="livres"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Etudiant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_etudiant", models.CharField(max_length=15)),
                ("prenom_etudiant", models.CharField(max_length=20)),
                ("mail_etudiant", models.EmailField(max_length=254)),
                ("contact_etudiant", models.CharField(max_length=15)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Emprunt",
            fields=[
                ("id_emprunt", models.AutoField(primary_key=True, serialize=False)),
                ("date_emprunt", models.DateField()),
                ("date_retour_prevue", models.DateField()),
                ("calcul_penalite", models.FloatField(default=0.0)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emprunts",
                        to="librairie.etudiant",
                    ),
                ),
                (
                    "livre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emprunts",
                        to="librairie.livre",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="etudiant",
            name="emprunter_livre",
            field=models.ManyToManyField(
                related_name="etudiants_emprunts",
                through="librairie.Emprunt",
                to="librairie.livre",
            ),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="rechecher_livre",
            field=models.ManyToManyField(
                related_name="etudiants_recherches", to="librairie.livre"
            ),
        ),
        migrations.CreateModel(
            name="Receptionniste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_receptionniste", models.CharField(max_length=15)),
                ("prenom_receptionniste", models.CharField(max_length=20)),
                ("mail_receptionniste", models.EmailField(max_length=254)),
                ("contact_receptionniste", models.CharField(max_length=15)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rapport",
            fields=[
                ("id_rapport", models.AutoField(primary_key=True, serialize=False)),
                ("date_rapport", models.DateField()),
                (
                    "livres_moins_empruntes",
                    models.ManyToManyField(
                        related_name="rapports_moins_empruntes", to="librairie.livre"
                    ),
                ),
                (
                    "livres_plus_empruntes",
                    models.ManyToManyField(
                        related_name="rapports_plus_empruntes", to="librairie.livre"
                    ),
                ),
                (
                    "receptionniste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapports",
                        to="librairie.receptionniste",
                    ),
                ),
            ],
        ),
    ]
