# Generated by Django 5.1 on 2024-08-16 15:22

import django.db.models.deletion
import librairie.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("librairie", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emprunt",
            name="calcul_penalite",
        ),
        migrations.AddField(
            model_name="emprunt",
            name="date_recuperation",
            field=models.DateField(default=librairie.models.date_recuperation_default),
        ),
        migrations.AlterField(
            model_name="emprunt",
            name="date_emprunt",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="emprunt",
            name="date_retour_prevue",
            field=models.DateField(default=librairie.models.date_retour_prevue_default),
        ),
        migrations.CreateModel(
            name="RetourLivre",
            fields=[
                ("id_retour", models.AutoField(primary_key=True, serialize=False)),
                ("date_retour_effective", models.DateField(auto_now_add=True)),
                ("penalite", models.FloatField(default=0.0)),
                (
                    "emprunt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retour",
                        to="librairie.emprunt",
                    ),
                ),
            ],
        ),
    ]
