# Generated by Django 5.1 on 2024-08-21 23:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("librairie", "0002_remove_emprunt_calcul_penalite_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retourlivre",
            name="date_retour_effective",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
